title: ColCh
description: Мой блог на Github

url: http://ColCh.github.com/
baseurl: /melAnim/

safe: true
auto: true

permalink: none

source: .
destination: ./_site

lsi: false
pygments: true

exclude:
  README.md
