title: ColCh
description: Мой блог на Github

url: http://ColCh.github.com/
baseurl: /melAnim/

safe: true
auto: true

permalink: none

source: .
destination: ./_site

lsi: false
pygments: true

exclude:
  README.md

post.template: default
post.extension: markdown

page.template: default
page.extension: markdown

editor: vim